Ydb exporter tests
ydb-platform/opentelemetry-collector-contrib pull request #1
Opened 2024-12-12 08:25 UTC by DenChika

**Description:** Refactored ydb-exporter a little bit and bringing the code to a working state

**Testing:** Written config and factories tests

2024-12-12 10:08 UTC, asmyasnikov commented on exporter/ydbexporter/config.go
> +	_ "github.com/ydb-platform/ydb-go-sdk/v3"
а зачем так делать?

2024-12-12 10:14 UTC, asmyasnikov commented on exporter/ydbexporter/factory.go
> +	"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/ydbexporter/internal/config"
линтер gofumpt здесь ругнется

2024-12-12 16:50 UTC, neyguvj requested changes

2024-12-12 16:50 UTC, neyguvj commented on exporter/ydbexporter/config.go
> +func WithDefaultConfig(fns ...func(*config.Config)) *config.Config {
обычно их называют opts/options

2024-12-12 16:50 UTC, neyguvj commented on exporter/ydbexporter/config_test.go
> +		id       component.ID
можно ещё добавить осмысленные имена тестам
тогда будет понятно, какой именно тест упал

2024-12-12 16:50 UTC, neyguvj commented on exporter/ydbexporter/factory_test.go
> +	// TODO: Uncomment after understanding problem with connecting to ydb
попробуй подключаться по 2136 без сертификатов
для тестов вполне норм

2024-12-12 16:50 UTC, neyguvj commented on exporter/ydbexporter/internal/db/factory.go
> +	errOnlyGrpcSupport         = errors.New("only gRPC and gRPCs schemes are supported")
константы - это хорошо
я на скорую руку делал в тот раз

2024-12-12 17:28 UTC, polRk requested changes

2024-12-12 17:28 UTC, polRk commented on exporter/ydbexporter/internal/db/factory.go
> +		return "", errOnlyGrpcSupport
Так не нужно. Нужно поддержать и ссылки вида http, https

2024-12-23 08:27 UTC, asmyasnikov commented on exporter/ydbexporter/internal/db/factory.go
> +		return "", errOnlyGrpcSupport
мы не пишем протокол/схему "http" и "https" для соединения с ydb. 
YDB работает по протоклу grpc

2024-12-23 08:29 UTC, asmyasnikov commented on exporter/ydbexporter/config.go
> +	defaultDatabase         = "/local"
давайте не будем разделять единый connection_string на endpoint+database?

2025-02-28 10:52 UTC, polRk commented
Лучше в конфигурация colelctor заменить отдельное endpoint + database на connection string. Люди в database могут забыть добавить лидирующий /

2025-05-14 05:31 UTC, closed without merging